### ISSUE TITLE
1.18.1 crash when placing fuel refinery 

### ISSUE THREAD

**Issue by 6unsatiable** [MrScautHD/Beyond-Earth#61]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 1/29/22, 2:59 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.save(net.minecraft.nbt.CompoundTag)'
	at net.mrscauthd.beyond_earth.machines.tile.AbstractMachineBlockEntity.save(AbstractMachineBlockEntity.java:175) ~[Beyond-Earth-1.18.1-6.0b.jar%2355!/:1.0] {re:classloading}
	at net.mrscauthd.beyond_earth.machines.tile.AbstractMachineBlockEntity.m_5995_(AbstractMachineBlockEntity.java:513) ~[Beyond-Earth-1.18.1-6.0b.jar%2355!/:1.0] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:153) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries.mixins.json:ChunkHolderMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1125) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:785) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_140192_(ChunkMap.java:923) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_140199_(ChunkMap.java:1045) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8463_(ServerChunkCache.java:458) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1551) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1534) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157575_(PersistentEntitySectionManager.java:135) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntityWithoutEvent(PersistentEntitySectionManager.java:98) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntityWithoutEvent(PersistentEntitySectionManager.java:76) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8853_(ServerLevel.java:827) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8834_(ServerLevel.java:771) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:190) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,re:classloading,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,pl:mixin:APP:ae2ao.mixins.json:PlayerListMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,re:classloading,pl:mixin:APP:krypton.mixins.json:shared.network.pipeline.encryption.ServerLoginNetworkHandlerMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,re:classloading,pl:mixin:APP:krypton.mixins.json:shared.network.pipeline.encryption.ServerLoginNetworkHandlerMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,re:classloading,pl:mixin:APP:krypton.mixins.json:shared.network.pipeline.encryption.ServerLoginNetworkHandlerMixin,pl:mixin:A}
	at net.minecraft.network.Connection.m_129483_(Connection.java:229) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,re:classloading,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ClientConnectionMixin,pl:mixin:APP:krypton.mixins.json:shared.network.pipeline.compression.ClientConnectionMixin,pl:mixin:APP:krypton.mixins.json:shared.network.pipeline.encryption.ClientConnectionMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

**Comment by MrScautHD** [comment]
Is already fuxed
